### ISSUE TITLE
Connect over SSH

### ISSUE THREAD

**Issue by vbr-cts** [StephenSorriaux/ansible-kafka-admin#104]
Hi,

I was wondering if there is a way to use this over ssh ? My use case is that I have single node kafka brokers, listening only on localhost, and need to manage those.

**Comment by ryarnyah** [comment]
Hi!

You can easily put your host in your playbook so the module will be running on your distant host.
With that you will need to install required dependencies to be present on your brokers hosts.

**Comment by ryarnyah** [comment]
@vbr-cts  Is that ok for you? If you have another question, feel free to talk with us on slack https://github.com/StephenSorriaux/ansible-kafka-admin#need-some-help
