### ISSUE TITLE
Output variable name difference for lib kafka_info is not optimal

### ISSUE THREAD

**Issue by Transrian** [StephenSorriaux/ansible-kafka-admin#118]
Hello,

For the *kafka_info* lib, this behavior is far from being optimal

> Depending on Ansible version, results will be saved under the **results** or **ansible_module_results key** (named <results_key> in below examples).

It should be the same whatever version of Ansible we use, and actually, the second name, for the most recents ansible version, is not very user-friendly

What about modifying it ? A simple change in this line to `whatever_variable_name=results` would do the trick, for the variable we could call `info` or something else

https://github.com/StephenSorriaux/ansible-kafka-admin/blob/672ffc91e3f14ca34c6481768215610f5ac4c136/library/kafka_info.py#L95

If you're ok with it, I can make a PR, for that and the doc (but would be a breaking change)

**Comment by StephenSorriaux** [comment]
Hi @Transrian,

PRs are always welcomed! :) 

I agree with you that this is not ideal. As far as I know, I noticed the change in the key name while updating the Ansible version used in our tests and just thought this was due to this Ansible update, without really checking it. If you have a solution in mind, we would really like to see it and, since `exit_json()` just takes some `kwargs` as arguments, maybe we can keep the current `results` key for some versions while also providing the new one.

**Comment by Transrian** [comment]
Just found the culprit code for the ansible update: [ansible/blob/devel/lib/ansible/plugins/action/__init__.py](https://github.com/ansible/ansible/blob/ee777567bcec859488c30f9c4c0f24ffcc0b9359/lib/ansible/plugins/action/__init__.py#L1110-L1114), introduced [here](https://github.com/ansible/ansible/issues/53962)

At first read, the reason:
> `results` is used internally to handle loops, so your module should never return this key

I guess we should avoid this output name then

> If you have a solution in mind, we would really like to see it and, since exit_json() just takes some kwargs as arguments, maybe we can keep the current results key for some versions while also providing the new one.

For now, while keeping the two version: `results` and a potentially new one, except by checking Ansible version (and compared it to when the patch was introduced, I don't see a good solution)

Some others library just changed their variable name to a new one, like [here](https://github.com/PaloAltoNetworks/pan-os-ansible/pull/108/commits/5a8b9afaa93ebbd6ebf85ca1b9b9c9727ea0c4fb), to mitigate the issue
