### ISSUE TITLE
Ansible-galaxy is not updated

### ISSUE THREAD

**Issue by Angelote2022** [StephenSorriaux/ansible-kafka-admin#142]
This library is pretty awesome, thanks for that. I noticed the changes are not pushed to ansible-galaxy.
Is there any reason to not continue pushing updates?

https://galaxy.ansible.com/stephensorriaux/kafka-admin

Latest up date was 5 years ago...

Many thanks

**Comment by StephenSorriaux** [comment]
Hello Angel,

Thanks for the nice word, happy to read this lib is useful :)

You are raising a very good point, we could just add a step in our release pipeline. Will look into that!
