### ISSUE TITLE
Missing asset in release 0.18.1

### ISSUE THREAD

**Issue by teebee** [StephenSorriaux/ansible-kafka-admin#156]
Is it intentional that there is no `StephenSorriaux-ansible_kafka_admin-0.18.1.tar.gz` asset in the latest [0.18.1](https://github.com/StephenSorriaux/ansible-kafka-admin/releases/tag/0.18.1) release?

**Comment by StephenSorriaux** [comment]
Hello,

Yes, I made a mistake in our GA pipeline and it was not released correctly. In the meantime another thing broke in the CI, I will try to fix it today.

**Comment by teebee** [comment]
Thank you for your quick reply. From my point of view there is no hurry.

**Comment by StephenSorriaux** [comment]
Hello,

The `0.18.2` version has just been released!
