### ISSUE TITLE
Add quotas management for KRaft-based clusters

### ISSUE THREAD

**Issue by andr1an** [StephenSorriaux/ansible-kafka-admin#159]
Quotas setup is supported in KRaft mode, you can use kafka-configs script for it, i.e.:

```bash
./bin/kafka-configs.sh \
  --bootstrap-server localhost:9092 --command-config ./config/kafka-admin-tools.properties \
  --alter --add-config producer_byte_rate=1024,request_percentage=50 \
  --entity-type users --entity-name myproducer 
```

But `kafka_quotas` module does not work without specifying Zookeeper-related arguments.

**Comment by ryarnyah** [comment]
Did you set `api_version` > 2.6.0?

**Comment by andr1an** [comment]
Thank you @ryarnyah, worked! I've just set `api_version: 3.6.0`, same as Kafka version I'm using.
