### ISSUE TITLE
Support for Kafka KRaft Clusters

### ISSUE THREAD

**Issue by chris-wood-mo** [StephenSorriaux/ansible-kafka-admin#174]
Are there any plans for this library to support Kafka KRaft clusters now Zookeeper is going EOL, I've currently tried to use this against a KRaft cluster it does create the topics/acl's as that particular section uses the bootstrap server, however when these are updated this is where it fails due to the fact that this section seems to only use the Zookeeper

**Comment by StephenSorriaux** [comment]
Hello,

Thanks for the issue.

I do believe the library is supporting KRaft clusters. ZK will not be needed/used if your are using a Kafka 3.x version and correctly configuring the `api_version` (to something like `3.X.Y`, the `auto` thingy is not working well) when using the library.

Please share logs/stacktraces if that is not the case.

**Comment by chris-wood-mo** [comment]
Hey Stephen,

I think this is what I've missed, thanks for the reply I'll give this a test and get back to you

**Comment by chris-wood-mo** [comment]
Thanks Stephen, All tested and works perfectly
