### ISSUE TITLE
Strange behavior of topic configuration update

### ISSUE THREAD

**Issue by teebee** [StephenSorriaux/ansible-kafka-admin#3]
Say you define the following options
```yaml
options:
    retention.ms: 66574936
    flush.ms: 564939
```
in your _playbook.yml_ and update the topic configuration.

Afterwards you decide to fall back to the global configuration value for ``flush.ms``. So you update your _playbook.yml_
```yaml
options:
    retention.ms: 66574936
```
and perform an update of the topic configuration. Since ``is_topic_configuration_need_update()`` checks only the given options it returns ``False``. Therefore ``update_topic_configuration()`` will not be called and the value of ``flush.ms`` is retained.

Later you modify the ``retention.ms``
```yaml
options:
    retention.ms: 574936
```
and perform another update of the topic configuration. Now ``is_topic_configuration_need_update()`` returns ``True`` and ``update_topic_configuration()`` changes the value of ``retention.ms`` **and** resets the value of  ``flush.ms``.

Was this behavior intentional?

**Comment by StephenSorriaux** [comment]
Hello,

Thanks for your question.

I may have misunderstood the Kafka protocol since it seemed to me that the AlterConfigs API will only update the given config entries and unchange the others. I will give a try on this. Currently this library does not handle the case when a topic configuration is deleted, I totally have to look into this but if you have some time, feel free to submit a PR :)

I come back to you after I do some tests

**Comment by teebee** [comment]
Thank you for your quick reply. I'm looking forward to your test results.

**Comment by teebee** [comment]
Due to [KIP-248](https://cwiki.apache.org/confluence/display/KAFKA/KIP-248+-+Create+New+ConfigCommand+That+Uses+The+New+AdminClient#KIP-248-CreateNewConfigCommandThatUsesTheNewAdminClient-AlterConfigs) there is currently an AlterConfigs version 1 in discussion which shall allow incremental operations (set/add/delete) on configs. The AlterConfigs version 0 protocol sets the whole properties object.

**Comment by StephenSorriaux** [comment]
You are totally right about the behaviour which was not intented as if. I just created a PR to fix that and better handle topics options (https://github.com/StephenSorriaux/ansible-kafka-admin/pull/4)

I am now using Zookeeper to manager topics options but I will add AlterConfigs version 1 when it will be out.

Feel free to give it a try and send me a feedback. I might merge the PR next week.

**Comment by teebee** [comment]
Great! I will try it and give you feedback. Thanks!

**Comment by teebee** [comment]
I reviewed and tested it: it looks good to me.

**Comment by StephenSorriaux** [comment]
Thank you, PR's merged!
