### ISSUE TITLE
Upgrade to Kafka API v1

### ISSUE THREAD

**Issue by sveba** [StephenSorriaux/ansible-kafka-admin#39]
It would be great if we could use the features of the new v1. For example the ACLs **resource-pattern-type** is a great feature

**Comment by StephenSorriaux** [comment]
Hi,

Thanks for this issue. You're right, this would be a nice feature. PR are welcomed if someone wants to spend some times on this feature.

**Comment by StephenSorriaux** [comment]
Fixed by https://github.com/StephenSorriaux/ansible-kafka-admin/pull/40
