### ISSUE TITLE
Docs indicate api_version is optional but code says it's required

### ISSUE THREAD

**Issue by nkonopinski** [StephenSorriaux/ansible-kafka-admin#48]
There's a delete topic example in the readme to use automatic api_version discovery. However, the code says it's a required field: https://github.com/StephenSorriaux/ansible-kafka-admin/blob/master/library/kafka_lib.py#L1603

It'd be great if it wasn't required and auto discovery worked!

**Comment by StephenSorriaux** [comment]
Hey @nkonopinski 

You are right this would definitely deserve some enhancements. If I remember well I wrote it this way because I got some weird behaviors when the api_version was not set correctly. But this was some times ago now, things should be better now.
