### ISSUE TITLE
Add cluster as resource type

### ISSUE THREAD

**Issue by BernhardBerbuir** [StephenSorriaux/ansible-kafka-admin#50]
## Expected Behavior

I want be able to manage operation `DESCRIBE_CONFIGS` for resource type _cluster_  
=> `acl_resource_type` should be expanded to include `cluster`

## Actual Behavior

It is not possible to manage operations for resource type _cluster_.

REMARK: not every operation supports resource type cluster (see [ACL Format](https://docs.confluent.io/current/kafka/authorization.html#acl-format) and [Operations and Resources on Protocols](https://kafka.apache.org/documentation/#operations_resources_and_protocols) for details)

**Comment by StephenSorriaux** [comment]
Hi,

Actually the `cluster` resource type is available under the name `broker`. But yes, we may need to correct that.
