### ISSUE TITLE
Licensing conflict Apache v2 versus GPL v3

### ISSUE THREAD

**Issue by vitkoma** [StephenSorriaux/ansible-kafka-admin#55]
## Expected Behavior
There are no conflicts between licenses used.

## Actual Behavior
The library is licensed under Apache License 2.0, but the kafka_lib.py and kafka_stat_lag.py files have GNU GPL v3.0 copyright in headers. 
If the library is a derivative work of a GPL software it can't be licensed under Apache v2 licence.

**Comment by StephenSorriaux** [comment]
Thank for this issue, I will see to resolve those conflicts.
